server:
  port: 10001

wecom:
  bot:
    webhook-url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e92445df-ef70-4bcd-8afa-215cd908fe17
  send-url: http://ikunbase.top:10001/api/wecom-bot/send-text
#  send-url: http://localhost:10001/api/wecom-bot/send-text
weather:
  key: 38865054ecab7d34d923674300e7d2bf
  city: 320100
  extensions: base

personalized:
  push:
    enable-greeting: true
    enable-weather-tip: true
    enable-clothing-suggestion: true
    enable-daily-message: true
    cron: 0 40 7 * * *
    city: 320100
    daily-message: 愿你的每一天都充满阳光和希望！
